person:
  age: 18
  boss: true
  birth: 2017/12/12
  last-name: johnny
  dog:
    age: 2
    name: tom
  maps: {k1: v1,k2: v2}
  lists:
    - lisi
    - wangwu

server:
  context-path: /boot
  port: 8081


logging:
  level:
    com:
      jiaolin:
        boot: debug
#    pattern:
  #    console:  %d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n
  #    file:  %d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n
  #        指定日志到文件以及文件到地址。
  #  file: /Users/johnny/logs/boot.log
  #  指定日志文件的路径,默认文件名为spring.log
  path: /Users/johnny/logs
