person:
  age: 18
  boss: true
  birth: 2017/12/12
  last-name: johnny
  dog:
    age: 2
    name: tom
  maps: {k1: v1,k2: v2}
  lists:
    - lisi
    - wangwu


spring:
  profiles:
    active: test
---
server:
  port: 8081

spring:
  profiles: test
---
server:
  port: 8082
spring:
  profiles: dev

---
server:
  port: 8083
spring:
  profiles: uat

---
server:
  port: 8084
spring:
  profiles: prd